# Generated by Django 5.0.2 on 2024-03-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0003_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='last_transaction_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='last_transaction_type',
            field=models.CharField(default='deposit', max_length=10),
        ),
    ]
