# Generated by Django 5.0.2 on 2024-03-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0004_profileuser_last_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='last_transaction_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
