# Generated by Django 5.0.3 on 2024-03-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0005_alter_profileuser_last_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
